### ISSUE TITLE
Import failure with errors

### ISSUE THREAD

**Issue by MartyNZ** [FabioParigi/NBrightBuyMigrate#3]
Tried to use this tool on NBrightBuy v3.5.2 and it failed with the following error:

"InnerMessage:Method not found: 'Void Nevoweb.DNN.NBrightBuy.Components.ProductData.Save()'.
InnerStackTrace:
at Nevoweb.DNN.NBrightBuyMigrate.Import.DoImport(NBrightInfo nbi)
at Nevoweb.DNN.NBrightBuyMigrate.Import.CtrlItemCommand(Object source, RepeaterCommandEventArgs e)
at System.Web.UI.WebControls.Repeater.OnItemCommand(RepeaterCommandEventArgs e)
at System.Web.UI.WebControls.Repeater.OnBubbleEvent(Object sender, EventArgs e)
at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
at System.Web.UI.WebControls.RepeaterItem.OnBubbleEvent(Object source, EventArgs e)
at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
at System.Web.UI.WebControls.LinkButton.OnCommand(CommandEventArgs e)
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)"

according to the NBrightBuy developer the

"...error message is saying the basic Save method of the product is not found. That method is the basic save method for a product, I'll assume you can save products form the BO? (Answer is yes)
This would probably mean this project needs compiling against the latest verison of NBSv3."

Is there a build of this tool that has been compiled against the current version of NBrightBuy?

If not, what is your recommended solution?

cheers
Martyn

**Comment by FabioParigi** [comment]
@MartyNZ 
Hi have you downloaded source and debug the plugin with Visual Studio?

**Comment by MartyNZ** [comment]
No. I’m not a developer…

Cheers
Martyn Cook
021 0221 2627
